"""Added Receiver model

Revision ID: 092a10f4de84
Revises: b1c77b2f230a
Create Date: 2024-02-21 01:05:09.886739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092a10f4de84'
down_revision: Union[str, None] = 'b1c77b2f230a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('blood_type_requirement', sa.String(length=3), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receivers')
    # ### end Alembic commands ###
